[0.037s] Invoking command in '/home/song/steadylab/src/build/zed_topic_benchmark_interfaces': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/song/steadylab/install/yo:/home/song/steadylab/install/steadylab:/opt/ros/foxy CONDA_PROMPT_MODIFIER=(base) /usr/bin/cmake --build /home/song/steadylab/src/build/zed_topic_benchmark_interfaces -- -j20 -l20
[0.212s] [  3%] Built target zed_topic_benchmark_interfaces__cpp
[0.213s] [ 12%] Built target zed_topic_benchmark_interfaces__rosidl_generator_c
[0.214s] [ 22%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_cpp
[0.214s] [ 32%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_fastrtps_cpp
[0.214s] [ 41%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_introspection_cpp
[0.214s] [ 51%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_introspection_c
[0.214s] [ 61%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_c
[0.214s] [ 70%] Built target zed_topic_benchmark_interfaces__rosidl_typesupport_fastrtps_c
[0.214s] [ 70%] Built target zed_topic_benchmark_interfaces
[0.214s] [ 74%] [34m[1mGenerating Python code for ROS interfaces[0m
[0.301s] ImportError in template '/opt/ros/foxy/share/rosidl_generator_py/cmake/../resource/_msg.py.em': 
[0.301s] 
[0.302s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.302s] 
[0.302s] Importing the numpy C-extensions failed. This error can happen for
[0.302s] many reasons, often due to issues with your setup or how NumPy was
[0.302s] installed.
[0.302s] 
[0.303s] We have compiled some common reasons and troubleshooting tips at:
[0.303s] 
[0.303s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.303s] 
[0.303s] Please note and check the following:
[0.303s] 
[0.303s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.303s]   * The NumPy version is: "1.23.1"
[0.303s] 
[0.303s] and make sure that they are the versions you expect.
[0.303s] Please carefully study the documentation linked above for further help.
[0.303s] 
[0.303s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.303s] 
[0.303s] ImportError when expanding '_idl.py.em' into '/home/song/steadylab/src/build/zed_topic_benchmark_interfaces/rosidl_generator_py/zed_topic_benchmark_interfaces/msg/_benchmark_stats_stamped.py': 
[0.303s] 
[0.303s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.303s] 
[0.303s] Importing the numpy C-extensions failed. This error can happen for
[0.303s] many reasons, often due to issues with your setup or how NumPy was
[0.304s] installed.
[0.304s] 
[0.304s] We have compiled some common reasons and troubleshooting tips at:
[0.304s] 
[0.304s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.304s] 
[0.304s] Please note and check the following:
[0.304s] 
[0.304s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.304s]   * The NumPy version is: "1.23.1"
[0.304s] 
[0.304s] and make sure that they are the versions you expect.
[0.304s] Please carefully study the documentation linked above for further help.
[0.304s] 
[0.304s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.304s] 
[0.304s] Error processing idl file: /home/song/steadylab/src/build/zed_topic_benchmark_interfaces/rosidl_adapter/zed_topic_benchmark_interfaces/msg/BenchmarkStatsStamped.idl
[0.304s] Traceback (most recent call last):
[0.304s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/__init__.py", line 23, in <module>
[0.304s]     from . import multiarray
[0.304s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/multiarray.py", line 10, in <module>
[0.304s]     from . import overrides
[0.304s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/overrides.py", line 6, in <module>
[0.304s]     from numpy.core._multiarray_umath import (
[0.304s] ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
[0.304s] 
[0.304s] During handling of the above exception, another exception occurred:
[0.305s] 
[0.305s] Traceback (most recent call last):
[0.305s]   File "/opt/ros/foxy/share/rosidl_generator_py/cmake/../../../lib/rosidl_generator_py/rosidl_generator_py", line 40, in <module>
[0.305s]     sys.exit(main())
[0.305s]   File "/opt/ros/foxy/share/rosidl_generator_py/cmake/../../../lib/rosidl_generator_py/rosidl_generator_py", line 36, in main
[0.305s]     return generate_py(args.generator_arguments_file, args.typesupport_impls.split(';'))
[0.305s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_generator_py/generate_py_impl.py", line 61, in generate_py
[0.305s]     generate_files(generator_arguments_file, mapping)
[0.305s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 96, in generate_files
[0.305s]     raise(e)
[0.305s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 87, in generate_files
[0.305s]     expand_template(
[0.305s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 149, in expand_template
[0.305s]     interpreter.string(template_content, template_path, locals=data)
[0.305s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2391, in string
[0.305s]     self.safe(scanner, True, locals)
[0.305s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2401, in safe
[0.305s]     self.parse(scanner, locals)
[0.305s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2421, in parse
[0.305s]     token.run(self, locals)
[0.305s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1547, in run
[0.305s]     self.subrun(info[0][1], interpreter, locals)
[0.305s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1631, in subrun
[0.305s]     token.run(interpreter, locals)
[0.305s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1425, in run
[0.306s]     interpreter.execute(self.code, locals)
[0.306s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2596, in execute
[0.306s]     _exec(statements, self.globals, locals)
[0.306s]   File "<string>", line 2, in <module>
[0.306s]   File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_cmake/__init__.py", line 198, in _expand_template
[0.306s]     interpreter.string(content, str(template_path), kwargs)
[0.306s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2391, in string
[0.306s]     self.safe(scanner, True, locals)
[0.306s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2401, in safe
[0.306s]     self.parse(scanner, locals)
[0.306s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2421, in parse
[0.306s]     token.run(self, locals)
[0.306s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 1425, in run
[0.306s]     interpreter.execute(self.code, locals)
[0.306s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2596, in execute
[0.306s]     _exec(statements, self.globals, locals)
[0.306s]   File "<string>", line 3, in <module>
[0.306s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
[0.306s]     from . import core
[0.306s]   File "/opt/ros/foxy/lib/python3.8/site-packages/numpy/core/__init__.py", line 49, in <module>
[0.306s]     raise ImportError(msg)
[0.306s] ImportError: 
[0.306s] 
[0.306s] IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
[0.306s] 
[0.306s] Importing the numpy C-extensions failed. This error can happen for
[0.306s] many reasons, often due to issues with your setup or how NumPy was
[0.306s] installed.
[0.306s] 
[0.306s] We have compiled some common reasons and troubleshooting tips at:
[0.306s] 
[0.307s]     https://numpy.org/devdocs/user/troubleshooting-importerror.html
[0.307s] 
[0.307s] Please note and check the following:
[0.307s] 
[0.307s]   * The Python version is: Python3.9 from "/home/song/anaconda3/bin/python3"
[0.307s]   * The NumPy version is: "1.23.1"
[0.307s] 
[0.307s] and make sure that they are the versions you expect.
[0.307s] Please carefully study the documentation linked above for further help.
[0.307s] 
[0.307s] Original error was: No module named 'numpy.core._multiarray_umath'
[0.307s] 
[0.309s] Exception ignored in: <function Interpreter.__del__ at 0x7f30513033a0>
[0.309s] Traceback (most recent call last):
[0.309s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2094, in __del__
[0.309s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2157, in shutdown
[0.309s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2647, in finalize
[0.309s]   File "/home/song/anaconda3/lib/python3.9/site-packages/em.py", line 2200, in push
[0.309s] AttributeError: '_io.TextIOWrapper' object has no attribute 'push'
[0.314s] make[2]: *** [zed_topic_benchmark_interfaces__py/CMakeFiles/zed_topic_benchmark_interfaces__py.dir/build.make:111: rosidl_generator_py/zed_topic_benchmark_interfaces/_zed_topic_benchmark_interfaces_s.ep.rosidl_typesupport_fastrtps_c.c] ì˜¤ë¥˜ 1
[0.314s] make[1]: *** [CMakeFiles/Makefile2:581: zed_topic_benchmark_interfaces__py/CMakeFiles/zed_topic_benchmark_interfaces__py.dir/all] ì˜¤ë¥˜ 2
[0.314s] make: *** [Makefile:141: all] ì˜¤ë¥˜ 2
[0.316s] Invoked command in '/home/song/steadylab/src/build/zed_topic_benchmark_interfaces' returned '2': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/song/steadylab/install/yo:/home/song/steadylab/install/steadylab:/opt/ros/foxy CONDA_PROMPT_MODIFIER=(base) /usr/bin/cmake --build /home/song/steadylab/src/build/zed_topic_benchmark_interfaces -- -j20 -l20
